# Generated by Django 5.1.5 on 2026-03-12 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(help_text='Main site URL')),
                ('rss_url', models.URLField(blank=True, help_text='RSS feed URL', null=True)),
                ('scraper_type', models.CharField(choices=[('rss', 'RSS Feed'), ('web', 'Web Scraper')], default='rss', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True, default='')),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('author', models.CharField(blank=True, default='', max_length=200)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('scraped_date', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False, help_text='Whether the AI extraction pipeline has processed this article')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.newssource')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
