# Generated by Django 5.1.5 on 2026-03-13 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='api_headers',
            field=models.JSONField(blank=True, help_text='JSON dictionary of headers to send with the request', null=True),
        ),
        migrations.AddField(
            model_name='newssource',
            name='api_mapping',
            field=models.JSONField(blank=True, help_text='JSON dictionary mapping response fields. \n        Example: {"items_path": "rows", "title_field": "title", "url_field": "url", "content_field": "presentation", "author_field": "author", "date_field": "published_date"}', null=True),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='rss_url',
            field=models.URLField(blank=True, help_text='RSS feed URL or API Endpoint URL', null=True),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='scraper_type',
            field=models.CharField(choices=[('rss', 'RSS Feed'), ('web', 'Web Scraper'), ('api', 'JSON API')], default='rss', max_length=10),
        ),
    ]
