# Generated by Django 5.1.5 on 2026-03-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_newssource_api_headers_newssource_api_mapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='max_articles_per_scrape',
            field=models.IntegerField(blank=True, help_text='Override the global max articles limit for this specific source', null=True),
        ),
    ]
