# Generated by Django 5.1.5 on 2026-03-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_newssource_max_articles_per_scrape'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='api_pagination',
            field=models.JSONField(blank=True, help_text='JSON pagination config. Example: {"enabled": true, "param": "o", "page_size": 100, "max_pages": 5}', null=True),
        ),
    ]
