# Generated by Django 5.1.5 on 2026-03-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_add_article_tags_image_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='historical_complete',
            field=models.BooleanField(default=False, help_text='Whether the initial historical backfill has been completed'),
        ),
        migrations.AddField(
            model_name='newssource',
            name='newest_article_date',
            field=models.DateTimeField(blank=True, help_text='Newest article publication date scraped from this source', null=True),
        ),
        migrations.AddField(
            model_name='newssource',
            name='oldest_article_date',
            field=models.DateTimeField(blank=True, help_text='Oldest article publication date scraped from this source', null=True),
        ),
        migrations.AddField(
            model_name='newssource',
            name='total_articles_scraped',
            field=models.IntegerField(default=0, help_text='Running count of articles successfully scraped'),
        ),
    ]
