# Generated by Django 5.1.5 on 2026-03-15 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_newssource_historical_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='raw_api_data',
            field=models.JSONField(blank=True, help_text='Raw JSON object from the API for this article (API sources only).', null=True),
        ),
    ]
