# Generated by Django 5.1.5 on 2026-03-15 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_add_article_raw_api_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='api_date_range',
            field=models.JSONField(blank=True, help_text='Date range params. Example: {"start_param": "d1", "end_param": "d2", "format": "%Y-%m-%d"}', null=True),
        ),
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('articles_found', models.IntegerField(default=0)),
                ('articles_new', models.IntegerField(default=0)),
                ('articles_skipped', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('pages_fetched', models.IntegerField(default=0)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_jobs', to='articles.newssource')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
