# Generated by Django 5.1.5 on 2026-03-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_add_date_range_and_scrape_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='processing_error',
            field=models.CharField(blank=True, default='', help_text='Last error message if AI extraction was attempted and failed (e.g. timeout, connection).', max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_processed',
            field=models.BooleanField(default=False, help_text='Whether the AI extraction pipeline has processed this article successfully'),
        ),
    ]
