# Generated by Django 5.1.5 on 2026-03-16 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_add_article_processing_error'),
        ('incidents', '0004_add_related_articles_and_is_duplicate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('articles', models.ManyToManyField(blank=True, related_name='stories', to='articles.article')),
                ('primary_incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='incidents.incident')),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'ordering': ['-updated_at'],
            },
        ),
    ]
