# Generated by Django 4.2.29 on 2026-03-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_add_story_model'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_processed'], name='articles_ar_is_proc_8ac836_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['published_date'], name='articles_ar_publish_0b76ae_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['source', 'published_date'], name='articles_ar_source__5b18db_idx'),
        ),
        migrations.AddIndex(
            model_name='newssource',
            index=models.Index(fields=['is_active', 'name'], name='articles_ne_is_acti_883582_idx'),
        ),
    ]
