# Generated by Django 5.1.5 on 2026-03-12 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('violent_crime', 'Violent Crime'), ('robbery', 'Robbery'), ('assault', 'Assault'), ('shooting', 'Shooting'), ('murder', 'Murder'), ('kidnapping', 'Kidnapping'), ('traffic_accident', 'Traffic Accident'), ('vehicle_collision', 'Vehicle Collision'), ('pedestrian_accident', 'Pedestrian Accident'), ('fire', 'Fire'), ('flood', 'Flood'), ('natural_disaster', 'Natural Disaster'), ('police_activity', 'Police Activity'), ('drug_related', 'Drug Related'), ('domestic_violence', 'Domestic Violence'), ('fraud', 'Fraud'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('location_name', models.CharField(blank=True, default='', max_length=300)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('region', models.CharField(choices=[('port_of_spain', 'Port of Spain'), ('san_fernando', 'San Fernando'), ('chaguanas', 'Chaguanas'), ('arima', 'Arima'), ('point_fortin', 'Point Fortin'), ('diego_martin', 'Diego Martin'), ('tunapuna_piarco', 'Tunapuna-Piarco'), ('san_juan_laventille', 'San Juan-Laventille'), ('couva_tabaquite_talparo', 'Couva-Tabaquite-Talparo'), ('sangre_grande', 'Sangre Grande'), ('siparia', 'Siparia'), ('penal_debe', 'Penal-Debe'), ('princes_town', 'Princes Town'), ('mayaro_rio_claro', 'Mayaro-Rio Claro'), ('tobago', 'Tobago'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('incident_date', models.DateTimeField(blank=True, null=True)),
                ('confidence_score', models.FloatField(default=0.0, help_text='AI extraction confidence (0–100)')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='articles.article')),
            ],
            options={
                'ordering': ['-incident_date', '-created_at'],
            },
        ),
    ]
