# Generated by Django 5.1.5 on 2026-03-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='fatality_count',
            field=models.IntegerField(default=0, help_text='Number of fatalities'),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_time',
            field=models.CharField(blank=True, default='', help_text='HH:MM 24h format', max_length=10),
        ),
        migrations.AddField(
            model_name='incident',
            name='suspect_description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='incident',
            name='vehicle_info',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='incident',
            name='victim_count',
            field=models.IntegerField(default=0, help_text='Number of victims (injured + killed)'),
        ),
        migrations.AddField(
            model_name='incident',
            name='weapon',
            field=models.CharField(blank=True, default='', help_text='Weapon used', max_length=100),
        ),
        migrations.AlterField(
            model_name='incident',
            name='confidence_score',
            field=models.FloatField(default=0.0, help_text='AI extraction confidence (0-100)'),
        ),
    ]
