# Generated by Django 5.1.5 on 2026-03-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_incident_fatality_count_incident_incident_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='ai_city',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='incident',
            name='ai_incident_date',
            field=models.DateTimeField(blank=True, help_text='Date extracted by AI (may be inaccurate, kept for analysis)', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='ai_location_raw',
            field=models.CharField(blank=True, default='', help_text='Raw location string as extracted by AI', max_length=500),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_date',
            field=models.DateTimeField(blank=True, help_text='Always set to article published_date for reliability', null=True),
        ),
    ]
