# Generated by Django 5.1.5 on 2026-03-16 13:33

import django.db.models.deletion
from django.db import migrations, models


def populate_related_articles(apps, schema_editor):
    """After migration: add primary_article to related_articles for each incident."""
    Incident = apps.get_model('incidents', 'Incident')
    for inc in Incident.objects.filter(primary_article_id__isnull=False):
        inc.related_articles.add(inc.primary_article_id)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_add_article_processing_error'),
        ('incidents', '0003_incident_ai_city_incident_ai_incident_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='article',
            new_name='primary_article',
        ),
        migrations.AddField(
            model_name='incident',
            name='is_duplicate',
            field=models.BooleanField(default=False, help_text='True if this incident was merged from a duplicate'),
        ),
        migrations.AddField(
            model_name='incident',
            name='related_articles',
            field=models.ManyToManyField(blank=True, help_text='All articles reporting this incident (including primary)', related_name='linked_incidents', to='articles.article'),
        ),
        migrations.RunPython(populate_related_articles, noop),
    ]
