# Generated by Django 5.1.5 on 2026-03-16 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_add_story_model'),
        ('incidents', '0004_add_related_articles_and_is_duplicate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='primary_article',
            field=models.ForeignKey(blank=True, help_text='First article that created this incident', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='articles.article'),
        ),
    ]
