# Generated by Django 5.1.5 on 2026-03-16 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_add_story_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='injured_count',
            field=models.IntegerField(default=0, help_text='Number injured (excluding fatalities)'),
        ),
        migrations.AddField(
            model_name='incident',
            name='is_resolved',
            field=models.BooleanField(default=False, help_text='True if arrests made or case resolved'),
        ),
        migrations.AddField(
            model_name='incident',
            name='motive',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='incident',
            name='premises_type',
            field=models.CharField(blank=True, default='', help_text='e.g. residence, business, road, school', max_length=50),
        ),
        migrations.AddField(
            model_name='incident',
            name='value_stolen',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated monetary value stolen (e.g. theft/robbery/fraud)', max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('victim', 'Victim'), ('suspect', 'Suspect'), ('witness', 'Witness'), ('arrested', 'Arrested')], max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=300)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('condition', models.CharField(choices=[('uninjured', 'Uninjured'), ('injured', 'Injured'), ('hospitalized', 'Hospitalized'), ('deceased', 'Deceased'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('occupation', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='incidents.incident')),
            ],
            options={
                'ordering': ['role', 'name'],
            },
        ),
    ]
