# Generated by Django 4.2.29 on 2026-03-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0006_add_person_and_incident_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status', 'incident_date'], name='incidents_i_status_64022f_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status', 'category'], name='incidents_i_status_0be33f_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status', 'region'], name='incidents_i_status_9251b1_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status', 'latitude', 'longitude'], name='incidents_i_status_cf06a6_idx'),
        ),
    ]
